### PR TITLE
Update game.py to change border rules

### PR DESCRIPTION
**Pull request by charkai**
Now, snake will die if it hits the defined border

### CODE REVIEW

**Comment by charkai** [comment]
NB: A further change must be made so that the snake is able to move 'along the edges' of the map. there may be a more effective way of managing this (It should have to do with the graphics, more than the logic.

**Comment by AbacusIsMad** [comment]
The snake segments are now expressed relative to the head, and are drawn appropriately. Unfortunately now the strawberries and walls don't work, but that too can be changed.

**Comment by AbacusIsMad** [comment]
yep, i forgot that one, will do

**Comment by charkai** [comment]
> yep, i forgot that one, will do

rockstar, thanks danny! I actually undid that comment because I realised i don't know if it makes anything easier..so if it's too complicated to do it that way don't sweat it. i think github works out any inconsistencies in the code and alerts you when you try to merge it anyway if it conflicts with something someoene else wrote, so even if we do have conflicts it shouldn't be an issue

**Pull request closed without merging**
